# Generated by Django 2.2.14 on 2021-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='Title',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='title',
            field=models.CharField(default='B', max_length=256),
        ),
    ]
